name: "HLF-$(Year:yyyy).$(Month).$(Date:dd)$(Rev:.r)"
# Note: This pipeline is based on documentation in: https://github.com/krypc-code/Hyperledger-Fabric-on-Azure-Kubernetes-Cluster

trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

parameters:
- name: deployResources
  displayName: Deploy Resources for Orderer and Peer
  type: boolean
  default: false # this is only required to be run once
- name: createConsortium
  displayName: Create the consortium
  type: boolean
  default: false # this is only required to be run once
- name: createChannelAndJoin
  displayName: Create the channel and join
  type: boolean
  default: false # this is only required to be run once

# Switches to control deployment individual chaincodes
- name: deployTestChaincode 
  displayName: Deploy the chaincode (Test)
  type: boolean
  default: true # this is required to be run everytime you do a change to the chaincode

variables:
  system.debugContext: false
  testChainCodeVersion: v1
  testChainCodeSequence: 1 # Important: This needs to increment each time a change to the chaincode is done and a new deployment of chain is required

stages:
  - template: templates/Hlf_complete_template.yaml
    parameters:
      deployResources: ${{ parameters.deployResources }}
      createConsortium: ${{ parameters.createConsortium }}
      createChannelAndJoin: ${{ parameters.createChannelAndJoin }}
      runNpmAudit: false
      deployTestChaincode: ${{ parameters.deployTestChaincode }}

      ######## SPN and Subscription ##########
      serviceConnection: your-service-connection-name-here
      hlfSubscription: 'your-sub-id' # Subscription which will house the HLF Orderer/Peer

      ####### Blob Storage and Resource Group ########
      blobStorageResourceGroup: some-name-here # this resource group must already be created
      blobName: somenamehere # this blob must already be created
      blobStorageKey: blah 
      blobStorageFileShare: some-name-here # this will be automatically created
      blobContainerName: some-name-here # this storage container must already be created

      ######## ACR ############
      dockerId: acr-name-here # this Azure Container Registry must already be created. Make sure "Admin user" is enabled in AccessKeys.
      dockerUsername: acr-name-here # docker admin user 
      dockerPwd: blah # docker admin pwd
      dockerImage: fabrictools:2.2.0 # name of the temporary tooling image

      ######## HLF specific #########
      hlfRegion: eastus
      hlfUserName: hlf-un # todo: remove hardcoded temp secret
      hlfCaPassword: blahblahblah123 # todo: remove hardcoded temp secret  
      hlfAksClusterPeer: hlf-aks-peer
      hlfAksClusterOrderer: hlf-aks-orderer
      hlfOrdererResourceGroup: some-name-for-orderer-rg-here # this will be automatically created
      hlfPeerResourceGroup: some-name-for-peer-rg-here # this will be automatically created
      hlfOrdererOrganization: MyOrdererName # must be alphanumeric due to script issues https://stackoverflow.com/questions/67980820/jq-produces-is-not-defined-at-top-level-error
      hlfPeerOrganization: MyPeerName # must be alphanumeric due to script issues https://stackoverflow.com/questions/67980820/jq-produces-is-not-defined-at-top-level-error
      hlfChannelName: mychannelname
      hlfNetworkName : myNetworkName
      hlfContextName : myContextName

      ######## Individual chaincode settings ########
      ######## Test Chaincode ###########
      testChainCodeVersion: ${{ variables.testChainCodeVersion }}
      testChainCodeSequence: ${{ variables.testChainCodeSequence }}